version: "3.3"
services:
  php:
    container_name: php
    build:
      context: ./Docker/config/php
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - ./src:/usr/share/nginx
      - ./Docker/config/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    networks:
      sample-network:

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    depends_on:
      - php
      - mysql
    ports:
      - "8088:80"
    volumes:
      - ./src:/usr/share/nginx
      - ./Docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      sample-network:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_ROOT_PASSWORD: '123456'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - "dbdata:/var/lib/mysql/"
      - "./Docker/db:/etc/mysql/my.cnf/"
      -  "./Docker/data/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      sample-network:

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      sample-network:


  artisan:
    build:
      context: ./Docker/config/php
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      sample-network:
networks:
  sample-network:
    driver: bridge
volumes:
  dbdata:
    driver: local